apiVersion: v1
kind: Pod
metadata:
  name: ps-init
  labels:
    app: initializer
spec:
  initContainers:
  - name: init-ctr
    image: busybox
    command: ['sh', '-c', 'until nslookup pluralsight-ftw; do echo waiting for pluralsight-ftw service; sleep 1; done; echo Service found!']
  containers:
    - name: web-ctr
      image: nigelpoulton/web-app:1.0
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pluralsight-ftw
spec:
  selector:
    app: initializer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
